INSERT INTO roles (id_role, name) VALUES (default, 'ROLE_ADMIN')
INSERT INTO roles (id_role, name) VALUES (default, 'ROLE_USER')
INSERT INTO roles (id_role, name) VALUES (default, 'ROLE_RESPONSABLE')

INSERT INTO type_of_requests (id_type, name) VALUES (default, 'Vacaciones')
INSERT INTO type_of_requests (id_type, name) VALUES (default, 'Permiso')

INSERT INTO causes (id_cause, description) VALUES (default, 'Matrimonio')
INSERT INTO causes (id_cause, description) VALUES (default, 'Nacimiento hijo/a')
INSERT INTO causes (id_cause, description) VALUES (default, 'Accidente o enfermedad grave')
INSERT INTO causes (id_cause, description) VALUES (default, 'Hospitalizacion o intervencion quirurgica sin hosp')
INSERT INTO causes (id_cause, description) VALUES (default, 'Traslado del domicilio habitual')
INSERT INTO causes (id_cause, description) VALUES (default, 'Compromiso inexcusable')
INSERT INTO causes (id_cause, description) VALUES (default, 'Situacion de excedente forzoso')
INSERT INTO causes (id_cause, description) VALUES (default, 'Compromiso sindical o representacion personal')
INSERT INTO causes (id_cause, description) VALUES (default, 'Casos medicos con bebes o adopcion')
INSERT INTO causes (id_cause, description) VALUES (default, 'Nacimiento prematuro del hijo/a')
INSERT INTO causes (id_cause, description) VALUES (default, 'Formacion del trabajador') 
INSERT INTO causes (id_cause, description) VALUES (default, 'Asistencia a examenes')
INSERT INTO causes (id_cause, description) VALUES (default, 'Derecho a vacaciones')
INSERT INTO causes (id_cause, description) VALUES (default, 'Vacaciones')

INSERT INTO schools (id_school, name) VALUES (default, 'Asturias')
INSERT INTO schools (id_school, name) VALUES (default, 'Madrid')
INSERT INTO schools (id_school, name) VALUES (default, 'Barcelona')
INSERT INTO schools (id_school, name) VALUES (default, 'Malaga')
INSERT INTO schools (id_school, name) VALUES (default, 'Sevilla')
INSERT INTO schools (id_school, name) VALUES (default, 'Norte')
